### ISSUE TITLE
Error on MacOS/Ubuntu Server

### ISSUE THREAD

**Issue by dataartisan** [pattertj/LoopTrader#71]
As soon as the new instance is started, the telegram gets 4 notifications, and fails with the following error.

2021-05-29 21:33:15,220 - sqliteDatabase.py - pre_flight_db_check() - INFO - Positions Table Created.
2021-05-29 21:33:15,221 - sqliteDatabase.py - pre_flight_db_check() - INFO - Orders Table Created.
2021-05-29 21:33:15,222 - sqliteDatabase.py - pre_flight_db_check() - INFO - Strategies Table Created.
2021-05-29 21:33:15,222 - sqliteDatabase.py - pre_flight_db_check() - INFO - Pre-Flight Checks Complete.
2021-05-29 21:33:16,316 - cspByDeltaStrategy.py - process_strategy() - DEBUG - processstrategy
2021-05-29 21:33:16,316 - cspByDeltaStrategy.py - get_market_session_loop() - DEBUG - get_market_session_loop
2021-05-29 21:33:16,678 - cspByDeltaStrategy.py - get_market_session_loop() - DEBUG - get_market_session_loop
2021-05-29 21:33:16,959 - cspByDeltaStrategy.py - get_market_session_loop() - DEBUG - get_market_session_loop
2021-05-29 21:33:17,250 - cspByDeltaStrategy.py - get_market_session_loop() - DEBUG - get_market_session_loop
2021-05-29 21:33:17,555 - cspByDeltaStrategy.py - process_strategy() - INFO - Markets are closed until 2021-06-01 13:30:00+00:00. Sleeping until 2021-06-01 13:28:00+00:00
2021-05-29 21:33:17,555 - botMediator.py - process_strategies() - INFO - Sleeping...
2021-05-29 21:33:38,427 - telegramnotifier.py - reply_text() - ERROR - Telegram failed to reply.
Traceback (most recent call last):
  File "/Users/s_pant/Desktop/backupmeup/autotrader/LoopTrader/looptrader/basetypes/Notifier/telegramnotifier.py", line 357, in reply_text
    message.reply_text(
  File "/usr/local/lib/python3.9/site-packages/telegram/message.py", line 689, in reply_text
    return self.bot.send_message(
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 127, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 475, in send_message
    return self._message(  # type: ignore[return-value]
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 296, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 259, in _post
    return self.request.post(
  File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 349, in post
    result = self._request_wrapper(
  File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 272, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities: character '.' is reserved and must be escaped with the preceding '\'
2021-05-29 21:34:15,797 - cspByDeltaStrategy.py - process_strategy() - DEBUG - processstrategy
2021-05-29 21:34:15,797 - cspByDeltaStrategy.py - process_strategy() - DEBUG - Markets Closed. Sleeping until 2021-06-01 13:28:00+00:00
2021-05-29 21:34:15,798 - botMediator.py - process_strategies() - INFO - Sleeping...
2021-05-29 21:35:15,801 - cspByDeltaStrategy.py - process_strategy() - DEBUG - processstrategy
2021-05-29 21:35:15,801 - cspByDeltaStrategy.py - process_strategy() - DEBUG - Markets Closed. Sleeping until 2021-06-01 13:28:00+00:00
2021-05-29 21:35:15,801 - botMediator.py - process_strategies() - INFO - Sleeping...
2021-05-29 21:36:15,801 - cspByDeltaStrategy.py - process_strategy() - DEBUG - processstrategy
2021-05-29 21:36:15,801 - cspByDeltaStrategy.py - process_strategy() - DEBUG - Markets Closed. Sleeping until 2021-06-01 13:28:00+00:00
2021-05-29 21:36:15,801 - botMediator.py - process_strategies() - INFO - Sleeping...
2021-05-29 21:41:56,416 - sqliteDatabase.py - pre_flight_db_check() - INFO - Pre-Flight Checks Complete.
2021-05-29 21:41:57,476 - cspByDeltaStrategy.py - process_strategy() - DEBUG - processstrategy
2021-05-29 21:41:57,476 - cspByDeltaStrategy.py - get_market_session_loop() - DEBUG - get_market_session_loop
2021-05-29 21:41:58,095 - cspByDeltaStrategy.py - get_market_session_loop() - DEBUG - get_market_session_loop
2021-05-29 21:41:58,578 - cspByDeltaStrategy.py - get_market_session_loop() - DEBUG - get_market_session_loop
2021-05-29 21:41:59,160 - cspByDeltaStrategy.py - get_market_session_loop() - DEBUG - get_market_session_loop
2021-05-29 21:41:59,891 - cspByDeltaStrategy.py - process_strategy() - INFO - Markets are closed until 2021-06-01 13:30:00+00:00. Sleeping until 2021-06-01 13:28:00+00:00
2021-05-29 21:41:59,891 - botMediator.py - process_strategies() - INFO - Sleeping...
2021-05-29 21:42:54,124 - sqliteDatabase.py - pre_flight_db_check() - INFO - Pre-Flight Checks Complete.
2021-05-29 21:42:55,140 - cspByDeltaStrategy.py - process_strategy() - DEBUG - processstrategy
2021-05-29 21:42:55,140 - cspByDeltaStrategy.py - get_market_session_loop() - DEBUG - get_market_session_loop
2021-05-29 21:42:55,475 - cspByDeltaStrategy.py - get_market_session_loop() - DEBUG - get_market_session_loop
2021-05-29 21:42:55,804 - cspByDeltaStrategy.py - get_market_session_loop() - DEBUG - get_market_session_loop
2021-05-29 21:42:56,117 - cspByDeltaStrategy.py - get_market_session_loop() - DEBUG - get_market_session_loop
2021-05-29 21:42:56,409 - cspByDeltaStrategy.py - process_strategy() - INFO - Markets are closed until 2021-06-01 13:30:00+00:00. Sleeping until 2021-06-01 13:28:00+00:00
2021-05-29 21:42:56,409 - botMediator.py - process_strategies() - INFO - Sleeping...
2021-05-29 21:43:32,940 - telegramnotifier.py - error() - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2021-05-29 21:43:38,167 - telegramnotifier.py - error() - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2021-05-29 21:43:44,413 - telegramnotifier.py - error() - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2021-05-29 21:43:52,119 - telegramnotifier.py - error() - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2021-05-29 21:43:54,605 - cspByDeltaStrategy.py - process_strategy() - DEBUG - processstrategy
2021-05-29 21:43:54,605 - cspByDeltaStrategy.py - process_strategy() - DEBUG - Markets Closed. Sleeping until 2021-06-01 13:28:00+00:00
2021-05-29 21:43:54,605 - botMediator.py - process_strategies() - INFO - Sleeping...
2021-05-29 21:43:59,090 - telegramnotifier.py - error() - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2021-05-29 21:44:09,498 - telegramnotifier.py - error() - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2021-05-29 21:44:24,912 - telegramnotifier.py - error() - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"

**Comment by dataartisan** [comment]
Error was fixed after a new credential file was generated outside of the application. Closing this issue, opening a new one.
