### ISSUE TITLE
Bot stops processing upon error

### ISSUE THREAD

**Issue by dataartisan** [pattertj/LoopTrader#78]
**Describe the bug**
I put an order for XSP in order to test this out. The 70% PT would have resulted in non-zero limitPrice. This caused the bot to stop responding, while the bot was running.

**To Reproduce**
Take a smaller delta on XSP and put an order, which would result in non-zero order for limit/closing price.

**Expected behavior**
Bot should continue processing despite error.

**Log**
Grabbing new access token...
ERROR - Failed to place order.
Traceback (most recent call last):
  File "/home/azureuser/LoopTrader/looptrader/basetypes/Broker/tdaBroker.py", line 260, in place_order
    orderresponse = self.getsession().place_order(
  File "/home/azureuser/.local/lib/python3.9/site-packages/td/client.py", line 1925, in place_order
    return self._make_request(method='post', endpoint=endpoint, mode='json', json=order, order_details=True)
  File "/home/azureuser/.local/lib/python3.9/site-packages/td/client.py", line 617, in _make_request
    raise NotNulError(message=response.text)
td.exceptions.NotNulError: {
  "error" : "non-zero limitPrice is required when orderType is Limit or Stop Limit"
}
Traceback (most recent call last):
  File "/home/azureuser/LoopTrader/looptrader/__main__.py", line 39, in <module>
    bot.process_strategies()
  File "/home/azureuser/LoopTrader/looptrader/basetypes/Mediator/botMediator.py", line 72, in process_strategies
    strategy.process_strategy()
  File "/home/azureuser/LoopTrader/looptrader/basetypes/Strategy/cspByDeltaStrategy.py", line 102, in process_strategy
    self.process_open_market(hours.end, now)
  File "/home/azureuser/LoopTrader/looptrader/basetypes/Strategy/cspByDeltaStrategy.py", line 142, in process_open_market
    self.place_new_orders_loop()
  File "/home/azureuser/LoopTrader/looptrader/basetypes/Strategy/cspByDeltaStrategy.py", line 430, in place_new_orders_loop
    neworder = self.build_new_order()
  File "/home/azureuser/LoopTrader/looptrader/basetypes/Strategy/cspByDeltaStrategy.py", line 295, in build_new_order
    int(position.symbol[-4:])
ValueError: invalid literal for int() with base 10: 'P413'

**Comment by dataartisan** [comment]
I will try again tomorrow, looks like the bot was actually processing despite of the error.

2021-06-01 13:43:17,355 - tdaBroker.py - place_order() - INFO - Your order being placed is: OrderedDict([('orderStrategyType', 'SINGLE'), ('orderType', 'LIMIT'), ('session', 'NORMAL'), ('duration', 'GOOD_TILL_CANCEL'), ('price', '0.0'), ('orderLegCollection', [{'instruction': 'BUY_TO_CLOSE', 'quantity': 1.0, 'instrument': {'assetType': 'OPTION', 'symbol': 'XSP_060221P413'}}])]) 
2021-06-01 13:43:17,544 - tdaBroker.py - place_order() - ERROR - Failed to place order.
Traceback (most recent call last):
  File "/home/azureuser/LoopTrader/looptrader/basetypes/Broker/tdaBroker.py", line 260, in place_order
    orderresponse = self.getsession().place_order(
  File "/home/azureuser/.local/lib/python3.9/site-packages/td/client.py", line 1925, in place_order
    return self._make_request(method='post', endpoint=endpoint, mode='json', json=order, order_details=True)
  File "/home/azureuser/.local/lib/python3.9/site-packages/td/client.py", line 617, in _make_request
    raise NotNulError(message=response.text)
td.exceptions.NotNulError: {
  "error" : "non-zero limitPrice is required when orderType is Limit or Stop Limit"
}
2021-06-01 13:43:17,558 - botMediator.py - process_strategies() - INFO - Sleeping...
2021-06-01 13:43:52,206 - cspByDeltaStrategy.py - process_strategy() - DEBUG - processstrategy
2021-06-01 13:43:52,206 - cspByDeltaStrategy.py - get_market_session_loop() - DEBUG - get_market_session_loop
2021-06-01 13:43:52,454 - cspByDeltaStrategy.py - process_open_market() - DEBUG - Processing Open-Market
2021-06-01 13:43:52,454 - cspByDeltaStrategy.py - process_expiring_positions() - DEBUG - process_expiring_positions
2021-06-01 13:43:52,454 - cspByDeltaStrategy.py - build_new_order() - DEBUG - build_new_order

**Comment by dataartisan** [comment]
Closed for now.
